LoadModule mesi_module /usr/lib/apache2/modules/mod_mesi.so

LogLevel debug

EnableMesi on
MesiAllowedHosts backend raw.githubusercontent.com
MesiBlockPrivateIPs Off

<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /var/www/html

    ProxyPreserveHost On
    ProxyPass /backend/ http://backend:8000/
    ProxyPassReverse /backend/ http://backend:8000/

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
