services:
  caddy:
    build:
      context: ../..
      dockerfile: servers/caddy/Dockerfile
    volumes:
      - ./Caddyfile.ci:/etc/caddy/Caddyfile
    ports:
      - 8080:8080
    depends_on:
      test-server:
        condition: service_started

  test-server:
    build:
      context: ../test-server
      dockerfile: Dockerfile
