services:
  traefik:
    image: go-mesi-traefik-test
    build:
      context: ../..
      dockerfile: servers/traefik/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./esi-configuration.yml:/esi-configuration.yml
    ports:
      - "8080:80"
    depends_on:
      - test-server

  test-server:
    image: crazygoat/esi-test-server
    labels:
      - traefik.http.routers.test-server.rule=Host(`domain.com`)
