version: '3.8'

services:
  traefik:
    image: traefik:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../..:/plugins-local/src/github.com/crazy-goat/go-mesi
      - ./traefik.yml:/traefik.yml
      - ./esi-configuration.yml:/esi-configuration.yml
    environment:
      GOPATH: /plugins-local
    ports:
      - 80:80
      - 8080:8080

  test-server:
    image: crazygoat/esi-test-server
    labels:
      - traefik.http.routers.test-server.rule=Host(`domain.com`)